version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-nextjs-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: Brunobetiatto
      POSTGRES_PASSWORD: Brunobetiatto1
      POSTGRES_DB: graphdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: