-- Allow private graph edges to use user-defined relation labels.
ALTER TABLE "PERSON_EDGE" ALTER COLUMN "relation" DROP NOT NULL;

CREATE TABLE "PERSON_RELATION_LABEL" (
    "id" TEXT NOT NULL,
    "treeId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PERSON_RELATION_LABEL_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "PERSON_EDGE" ADD COLUMN "relationLabelId" TEXT;

CREATE UNIQUE INDEX "PERSON_RELATION_LABEL_treeId_name_key" ON "PERSON_RELATION_LABEL"("treeId", "name");

ALTER TABLE "PERSON_RELATION_LABEL" ADD CONSTRAINT "PERSON_RELATION_LABEL_treeId_fkey" FOREIGN KEY ("treeId") REFERENCES "PERSON_TREE"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "PERSON_EDGE" ADD CONSTRAINT "PERSON_EDGE_relationLabelId_fkey" FOREIGN KEY ("relationLabelId") REFERENCES "PERSON_RELATION_LABEL"("id") ON DELETE SET NULL ON UPDATE CASCADE;
