ALTER TABLE "NODE_REQUEST_CONN" ADD COLUMN "documentTitle" TEXT;
ALTER TABLE "NODE_REQUEST_CONN" ADD COLUMN "documentContent" TEXT;
ALTER TABLE "NODE_REQUEST_CONN" ADD COLUMN "documentImageUrl" TEXT;

ALTER TABLE "GLOBAL_EDGE" ADD COLUMN "documentTitle" TEXT;
ALTER TABLE "GLOBAL_EDGE" ADD COLUMN "documentContent" TEXT;
ALTER TABLE "GLOBAL_EDGE" ADD COLUMN "documentImageUrl" TEXT;
