ALTER TABLE "NODE_REQUEST" ADD COLUMN "nodeTagSlug" TEXT NOT NULL DEFAULT 'person';
ALTER TABLE "GLOBAL_NODE" ADD COLUMN "tagSlug" TEXT NOT NULL DEFAULT 'person';

CREATE INDEX "GLOBAL_NODE_tagSlug_idx" ON "GLOBAL_NODE"("tagSlug");
